name: frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^7.0.1
  flutter_web3: ^2.1.9
  provider: ^6.0.5
  flutter_svg: ^2.0.5
  figma_squircle: ^0.5.3
  http: ^0.13.6
  dropdown_button2: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
      - family: BasierCircle
        fonts:
        - asset: assets/BasierCircle-Regular.otf
      - family: ClashDisplay
        fonts:
        - asset: assets/ClashDisplay-Semibold.ttf
  uses-material-design: true
  assets:
     - assets/
  