# Generated by Django 4.2.1 on 2023-05-13 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.IntegerField(null=None)),
                ('wallet_address', models.CharField(db_index=True, editable=False, max_length=42, unique=True, validators=[django.core.validators.MinLengthValidator(42)])),
                ('name', models.CharField(max_length=200)),
                ('contract_address', models.CharField(db_index=True, editable=False, max_length=42, unique=True, validators=[django.core.validators.MinLengthValidator(42)])),
            ],
        ),
    ]
