# Generated by Django 4.2.1 on 2023-05-13 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contract_address',
            field=models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='wallet_address',
            field=models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)]),
        ),
    ]
