# Generated by Django 4.2.1 on 2023-05-13 21:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_account_contract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42, null=True, validators=[django.core.validators.MinLengthValidator(42)])),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.account')),
            ],
        ),
    ]
